name: Junit Annotate
description: Annotates your build using JUnit XML reports
author: https://github.com/buildkite
requirements:
  - docker
configuration:
  properties:
    artifacts:
      type: string
    always-annotate:
      type: boolean
    context:
      type: string
    failure-format:
      type: string
      enum:
        - classname
        - file
    fail-buil