steps:
  - label: ":bash: Plugin"
    plugins:
      docker-compose#v4.9.0:
        run: plugin
  - label: ":ruby: Ruby"
    plugins:
      docker-compose#v4.9.0:
        run: ruby
  - label: "✨ Lint"
    plugins:
      plugin-lint